FROM python:3.11-slim AS builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libpq-dev \
    libffi-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

COPY manage.py .
COPY config ./config/
COPY apps ./apps/

# Runtime stage
FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY --from=builder /app/manage.py .
COPY --from=builder /app/config ./config/
COPY --from=builder /app/apps ./apps/


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libpq5 && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m appuser && chown -R appuser:appuser /app

USER appuser

CMD sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"