# Generated by Django 5.1.4 on 2025-01-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField(null=True)),
                ('latest_date', models.DateField(null=True)),
                ('source_file', models.CharField(max_length=255)),
            ],
        ),
    ]
