# Generated by Django 5.1.4 on 2025-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='stock_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
