# Generated by Django 5.1.4 on 2025-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_stockdata_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='isEtf',
            field=models.BooleanField(default=False),
        ),
    ]
