# Generated by Django 5.1.4 on 2025-01-22 04:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_stockdata_isetf'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='market_data_search__f0d0dd_gin'),
        ),
    ]
