# Generated by Django 5.1.4 on 2025-01-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_stockdata_search_vector_and_more'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;"),
    ]
