# Generated by Django 5.1.4 on 2025-01-23 06:19

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_auto_20250123_0604'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdata',
            name='market_data_search__f0d0dd_gin',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='search_vector',
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['symbol'], name='stockdata_trgm_symbol_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['stock_name'], name='stockdata_trgm_stock_name_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
